[server]
follow_symlink = false
browser = "default"

[keymap]
preset = "default"
[keymap.overrides]

[runtime]
auto_instantiate = true
on_cell_change = "autorun"
auto_reload = "off"

[package_management]
manager = "pip"

[display]
code_editor_font_size = 14
cell_output = "above"
theme = "dark"
dataframes = "rich"
default_width = "medium"

[completion]
copilot = false
activate_on_typing = true

[formatting]
line_length = 79

[ai]
rules = ""

[experimental]

[save]
autosave_delay = 1000
format_on_save = false
autosave = "after_delay"
